package com.revature.hello;

public class AboutExceptions {
	
	public static void main(String[] args) {
		
		int[] arr = new int[4];
		
		try{
			arr[0] = 1;
			arr[6] = 6;
		}catch(ArrayIndexOutOfBoundsException e){
			e.printStackTrace();
		}
		
		
		System.out.println("Passed Exception!");
	}

}
