package Day2;

public class understanding_throw_exceptions {
	public static void main(String[] args)
	{
		int[] arr = new int[4];
		arr[0]=1;
		arr[6]=6;
	}
}
