package com.ex.probs;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

public class CodingChallengesTest {
	
	private CodingChallenges c;
	
	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		System.out.println("Before Class");
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
		System.out.println("After Class");
	}

	@Before
	public void setUp() throws Exception {
		c = new CodingChallenges();
		System.out.println("Before Method");
	}

	@After
	public void tearDown() throws Exception {
		c = null;
		System.out.println("After Method");
	}

	@Test
	public void testFactorial() {
		int expected = 120;
		int actual = c.factorial(5);
		//System.out.println(actual);
		testAssertEquals(expected, actual, "5! equals 120");
		
	}
	
	@Test
	public void testFactorialZero(){
		assertNotEquals(1, c.factorial(5));
	}
	
	@Test
	public void testReverseString(){
		testAssertEquals("stop", c.reverse("pots"), "stop equals pots in reverse");
	}
	
	public void testAssertEquals(Object x, Object y, String message){
		
		try{
			assertEquals(x, y);
			System.out.println();
			System.out.println(message + " -passed");
		}catch(AssertionError e){
			System.out.println();
			System.out.println(message + " -failed");
		}
	}

}
